apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}-{{ .Values.image.frontend | replace ":" "-" }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Chart.Name }}
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}
    spec:
      containers:
      - name: frontend
        image: {{ .Values.image.frontend }}
        ports:
        - containerPort: {{ .Values.service.frontendPort }}
      - name: backend
        image: {{ .Values.image.backend }}
        ports:
        - containerPort: {{ .Values.service.backendPort }}
